#!/bin/bash
#source /var/lib/premium-script/settvps.conf
#echo "Permission Accepted"
#sleep 1
clear
echo ""
tls="$(cat ~/log-install.txt | grep -w "Vless TLS" | cut -d: -f2|sed 's/ //g')"
none="$(cat ~/log-install.txt | grep -w "Vless None TLS" | cut -d: -f2|sed 's/ //g')"
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
user=trial-`</dev/urandom tr -dc X-Z0-9 | head -c3`
		#read -rp "User: " -e user
		CLIENT_EXISTS=$(grep -w $user /etc/v2ray/vless.json | wc -l)

		if [[ ${CLIENT_EXISTS} == '1' ]]; then
			echo ""
			echo "A client with the specified name was already created, please choose another name."
			exit 1
		fi
	done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
exp=`date -d "$masaaktif hour" +"%R"`
created=`date -d "0 days" +"%d-%m-%Y"`
sed -i '/#tls$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/v2ray/vless.json
sed -i '/#none$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/v2ray/vnone.json
vlesslink1="vless://${uuid}@${domain}:$tls?path=geo&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:$none?path=geo&encryption=none&type=ws#${user}"
systemctl restart v2ray@vless
systemctl restart v2ray@vnone
clear

echo -e "Success!"
echo -e "==========================" | lolcat
echo -e "${OWNER}"
echo -e "         • VLESS •        "
echo -e "==========================" | lolcat
echo -e "Remarks        : ${user}"
echo -e "Domain         : ${domain}"
echo -e "port TLS       : $tls"
echo -e "port none TLS  : $none"
echo -e "id             : ${uuid}"
echo -e "Encryption     : none"
echo -e "network        : ws"
echo -e "path           : geo"
echo -e "==========================" | lolcat
echo -e "Masa Aktif     : $masaaktif Jam"
echo -e "Expaired       : $exp WIB"
echo -e "==========================" | lolcat
echo -e "link TLS       : ${vlesslink1}"
echo -e "==========================" | lolcat
echo -e "link none TLS  : ${vlesslink2}"
echo -e "==========================" | lolcat
echo -e "${PESAN}"
echo -e ""
